import { v4 as uuidv4 } from 'uuid';

export const addDataBase = firebase => {
  const dataBase = firebase.firestore();
  /* men
    ============================================ */

  // Category: Tops
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop-cut lux',
  //   route: 'drop-cut-lux',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description: 'Cool touch, high-cotton LUX Blend fabric.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: [
  //     'subtle',
  //     'white',
  //     'black',
  //     'heather grey',
  //     'forest',
  //     'stone',
  //     'navy',
  //     'maroon',
  //     'light heather grey',
  //     'dark heather grey',
  //     'sand',
  //     'olive',
  //     'charcoal',
  //     'atlantic',
  //     'moss',
  //     'mist',
  //     'pebble',
  //     'valencia',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: false },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop-cut shirt',
  //   route: 'drop-cut-shirt',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'bylt blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'Meet the new and improved BYLT Blend fabric in your favorite signature drop-cut short sleeve shirt. We have worked hard to take your favorite style to the next level of comfort, fit, & functionality.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: [
  //     'black',
  //     'white',
  //     'navy',
  //     'moss',
  //     'charcoal',
  //     'maroon',
  //     'sand',
  //     'olive',
  //     'atlantic',
  //     'mist',
  //     'pebble',
  //     'valencia',
  //     'subtle',
  //     'forest',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: false },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop-cut lux pocket',
  //   route: 'drop-cut-lux-pocket',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'Athletic and comfortable cut with our signature drop-cut hemline featuring our new high-cotton LUX Blend fabric.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: [
  //     'mist subtle',
  //     'navy mist',
  //     'dark heather grey pebble',
  //     'pink ice subtle',
  //     'atlantic pebble',
  //     'subtle valencia',
  //     'white mist',
  //     'forest bone',
  //     'navy swell',
  //     'bone navy',
  //     'maroon bone',
  //     'stone pacific',
  //     'pacific slate',
  //     'black charcoal',
  //     'charcoal black',
  //     'forest black',
  //     'sand pink ice',
  //     'dusk dark heather grey',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'striped drop-cut lux',
  //   route: 'striped-drop-cut-lux',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     "Elevated to a whole new level, your favorite Drop-Cut: LUX Shirt is made complete with a newly innovative striped pattern. This 'Striped Drop-Cut: LUX' is the perfect way to upgrade your everyday style.",
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: [
  //     'mist bone',
  //     'atlantic pebble',
  //     'pebble atlantic',
  //     'charcoal bone',
  //     'forest black',
  //     'navy bone',
  //     'black grey',
  //     'bone navy',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'striped drop-cut v-neck lux',
  //   route: 'striped-drop-cut-v-neck-lux',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'v-necks',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'A fresh new take on your classic V-Neck. Your favorite style has been elevated with a V-neck collar and our signature Drop-Cut hemline perfected with the LUX fabric you love.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: ['bone navy', 'charcoal bone', 'black grey'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'henley drop cut lux',
  //   route: 'henley-drop-cut-lux',
  //   collections: 'mens-tops',
  //   style: 'henleys',
  //   cut: 'drop-cuts',
  //   neck: 'henleys',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 3899,
  //   description:
  //     'Enjoy the best selling Drop-Cut shirt transformed into a short sleeve Henley. Our Henley Drop-Cut is here to add character and versatility to your wardrobe. This shirt is the peak of style, comfort, and function.',
  //   images: ['1.jpg', '2.jpg', '3.jpg'],
  //   colors: [
  //     'white',
  //     'black',
  //     'navy',
  //     'heather grey',
  //     'dark heather grey',
  //     'maroon',
  //     'iris',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'training shorts',
  //   route: 'training-shorts',
  //   collections: 'mens-bottoms',
  //   style: 'shorts',
  //   fabric: 'performance',
  //   date: new Date().getTime(),
  //   price: 7499,
  //   description:
  //     "Made from our NEW lightweight, breathable and ultra-stretch Performance Blend fabric, the new Training Short is built to withstand your most active days. Feel the difference that's sure to never slow you down during those high intensity training sessions.",
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'storm-camo', 'asphalt-camo', 'forest camo', 'charcoal'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: "men's elite+ drop-cut pullover",
  //   route: 'men-elite-drop-cut-pullover',
  //   collections: 'outerwear',
  //   style: 'pullovers',
  //   cut: 'drop-cuts',
  //   neck: 'hooded',
  //   sleeve: 'long sleeves',
  //   fabric: 'elite+',
  //   date: new Date().getTime(),
  //   price: 8999,
  //   description:
  //     "Made for complete comfort in all climates, our Drop-Cut Elite+ Pullover has been re-imagined in ultimate style. Now with even greater comfort, breathability, and complete all around flexibility, you've found your new go-to pullover for all seasons!",
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'gunmetal', 'dark olive', 'sand', 'black', 'midnight'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'everyday hat',
  //   route: 'everyday-hat',
  //   collections: 'hats-accessories',
  //   style: 'hats',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'The 100% Cotton Everyday Cap features an adjustable antique brass buckle closure to ensure the perfect fit.',
  //   images: ['1.jpg', '2.jpg', '3.jpg'],
  //   colors: ['white', 'black'],
  //   sizes: [{ size: 'os', isAvailable: true }],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'allday boxer briefs',
  //   route: 'allday-boxer-briefs',
  //   collections: 'underwear',
  //   style: 'boxer briefs',
  //   fabric: 'all day',
  //   date: new Date().getTime(),
  //   price: 2599,
  //   description:
  //     'Our AllDay Boxer Brief Underwear style has been completely upgraded! Now in all around enhanced fabric, experience improved support with all day breathability and ultimate comfort. ',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: [
  //     'black',
  //     'sky blue navy',
  //     'forest camo',
  //     'dark olive',
  //     'asphalt camo',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // SNOW WASH COLLECTION
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'snow wash drop-cut',
  //   route: 'snow-wash-drop-cut',
  //   collections: 'mens-tops',
  //   snowWashCollection: true,
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'As soft as fresh powder, our Snow Wash is made with a unique dye effect that adds a subtle dusted textured look all with an even softer hand feel.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['forest', 'maroon', 'olive', 'navy', 'charcoal'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: false },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'snow wash drop-cut long sleeve',
  //   route: 'snow-wash-drop-cut-long-sleeve',
  //   collections: 'mens-tops',
  //   snowWashCollection: true,
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'long sleeves',
  //   fabric: 'bylt blend',
  //   date: new Date().getTime(),
  //   price: 3699,
  //   discountPer: 20,
  //   description:
  //     'As soft as fresh powder, our Snow Wash is made with a unique dye effect that adds a subtle dusted textured look all with an even softer hand feel. Please note - This item is EXCHANGE ONLY and not eligible for return.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['olive', 'forest', 'maroon', 'navy', 'charcoal'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // PERFORMANCE COLLECTION
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'circuit tank',
  //   route: 'circuit-tank',
  //   collections: 'mens-tops',
  //   performanceCollection: true,
  //   style: 'tanks',
  //   cut: 'drop-cuts',
  //   neck: 'hooded',
  //   sleeve: 'no sleeves',
  //   fabric: 'performance',
  //   date: new Date().getTime(),
  //   price: 4499,
  //   discountPer: 20,
  //   description:
  //     'A Hooded Henley style lighter than ever before, the Circuit Tank is a defining style to take your active looks, and results, to the next level.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'dark olive', 'asphalt camo'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'the circuit hoodie',
  //   route: 'the-circuit-hoodie',
  //   collections: 'mens-tops',
  //   performanceCollection: true,
  //   style: 'henleys',
  //   cut: 'drop-cuts',
  //   neck: 'henleys',
  //   sleeve: 'long sleeves',
  //   fabric: 'performance',
  //   date: new Date().getTime(),
  //   price: 6999,
  //   description:
  //     'Our best selling Hooded Henley has been taken to a completely new level with durable, lightweight, ultra-stretch performance grade fit and fabric.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'black', 'dark olive', 'asphalt camo'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: "men's elite+ jogger shorts",
  //   route: 'mens-elite-jogger-shorts',
  //   collections: 'mens-bottoms',
  //   performanceCollection: true,
  //   style: 'shorts',
  //   fabric: 'premium',
  //   date: new Date().getTime(),
  //   price: 6999,
  //   description:
  //     'The perfect combination of performance and comfort, the Elite+ Jogger Shorts offer an athletic fit with all the qualities you need in our most easy to wear style.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['heather grey', 'black', 'dark olive', 'gunmetal'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'performance drop-cut long sleeve shirt',
  //   route: 'performance-drop-cut-long-sleeve shirt',
  //   collections: 'mens-tops',
  //   performanceCollection: true,
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'long sleeves',
  //   fabric: 'performance',
  //   date: new Date().getTime(),
  //   price: 4099,
  //   description:
  //     'Your favorite Drop-Cut Long Sleeve style now in an entirely enhanced fabric. Made from our new lightweight, breathable and ultra-stretch Performance Blend fabric, the Performance Drop-Cut Long Sleeve is built to withstand your all weather active days.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'black'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // Men's Executive Collection
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'executive polo',
  //   route: 'executive-polo',
  //   collections: 'mens-tops',
  //   executiveCollection: true,
  //   style: 'polos',
  //   cut: 'drop-cuts',
  //   neck: 'polos',
  //   sleeve: 'short sleeves',
  //   fabric: 'executive',
  //   date: new Date().getTime(),
  //   price: 6499,
  //   description:
  //     'We’ve completely reinvented our most sophisticated styles in every way now perfected for the modern man. From the course to the afternoon out, our fully upgraded Executive Collection offers a new definition to an all around refined comfort style.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['olive', 'black', 'white', 'navy'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop tech polo',
  //   route: 'drop-tech-polo',
  //   collections: 'mens-tops',
  //   executiveCollection: true,
  //   style: 'polos',
  //   cut: 'drop-cuts',
  //   neck: 'polos',
  //   sleeve: 'short sleeves',
  //   fabric: 'tech',
  //   date: new Date().getTime(),
  //   price: 6499,
  //   description:
  //     'Designed for both performance and ultimate comfort, featuring a sweat resistant outer layer and a super soft inner layer.',
  //   images: ['1.jpg', '2.jpg', '3.jpg'],
  //   colors: ['gunmetal', 'black', 'navy'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: false },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'everyday pant 2.0',
  //   route: 'everyday-pant-2.0',
  //   collections: 'mens-bottoms',
  //   executiveCollection: true,
  //   style: 'pants',
  //   fabric: 'elite+',
  //   date: new Date().getTime(),
  //   price: 10999,
  //   description:
  //     'The best selling Everyday Pant is back and better than ever before. Improved in every way with our ultra-stretch Elite+ Fabric for the highest level of all day comfort and an all around upgraded fit.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'black', 'charcoal', 'navy'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'kinetic shorts',
  //   route: 'kinetic-shorts',
  //   collections: 'mens-bottoms',
  //   executiveCollection: true,
  //   style: 'shorts',
  //   date: new Date().getTime(),
  //   price: 8499,
  //   description:
  //     'Your everyday casual shorts elevated to a whole new level of premium comfort. Perfect for an afternoon out or while on the course, The Kinetic Shorts offer flexibility and versatility making them your new go-to for any occasion.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['iron', 'storm', 'navy', 'dark olive'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // Men's Summer Dye Collection
  dataBase.collection('men').add({
    id: uuidv4(),
    gender: 'men',
    name: 'cloud dye drop-cut',
    route: 'cloud-dye-drop-cut',
    collections: 'mens-tops',
    summerDye: true,
    style: 'drop-cuts',
    cut: 'drop-cuts',
    neck: 'crews',
    sleeve: 'short sleeve',
    fabric: 'lux blend',
    date: new Date().getTime(),
    price: 3199,
    description:
      'A step away from our traditional solids and joining our catalog of unique prints, patterns and washes comes the latest addition to our Drop-Cut Lineup: Meet the Cloud Dye Tee.',
    images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
    colors: ['charcoal-cloud', 'sand-cloud', 'black-cloud', 'sky-blue-cloud'],
    sizes: [
      { size: 's', isAvailable: true },
      { size: 'm', isAvailable: true },
      { size: 'l', isAvailable: true },
      { size: 'xl', isAvailable: true },
      { size: 'xxl', isAvailable: true },
    ],
    stock: 25,
    popularity: false,
  });

  dataBase.collection('men').add({
    id: uuidv4(),
    gender: 'men',
    name: 'prism dye drop-cut',
    route: 'prism-dye-drop-cut',
    collections: 'mens-tops',
    summerDye: true,
    style: 'drop-cuts',
    cut: 'drop-cuts',
    neck: 'crews',
    sleeve: 'short sleeve',
    fabric: 'lux blend',
    date: new Date().getTime(),
    price: 3199,
    description:
      'A step away from our traditional solids and joining our catalog of unique prints, patterns and washes comes the latest addition to our Drop-Cut Lineup: Meet the Prism Dye Tee.',
    images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
    colors: ['white-storm-prism', 'black-charcoal-prism', 'navy-bone-prism'],
    sizes: [
      { size: 's', isAvailable: true },
      { size: 'm', isAvailable: true },
      { size: 'l', isAvailable: true },
      { size: 'xl', isAvailable: true },
      { size: 'xxl', isAvailable: true },
    ],
    stock: 25,
    popularity: false,
  });

  /* women
    ============================================ */

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's elite + joggers",
  //   route: "women's-elite-joggers",
  //   collections: 'womens-bottoms',
  //   style: 'joggers',
  //   fabric: 'elite+',
  //   date: new Date().getTime(),
  //   price: 7499,
  //   description:
  //     "Reimagined in every way, our Women’s Elite+ Joggers have been completely upgraded for even greater comfort, added durability, and all around flexibility. With the new Elite+ Fabric perfect for any season, you'll never want to take these joggers off!",
  //   images: [
  //     '1.jpg',
  //     '2.jpg',
  //     '3.jpg',
  //     '4.jpg',
  //     '5.jpg',
  //     '6.jpg',
  //     '7.jpg',
  //     '8.jpg',
  //     '9.jpg',
  //   ],
  //   colors: ['black', 'dark olive', 'sand', 'gunmetal', 'storm', 'midnight'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential drop-cut tank",
  //   route: "women's-essential-drop-cut-tank",
  //   collections: 'womens-tops',
  //   style: 'tanks',
  //   fabric: 'bylt blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'An all around flattering athletic-fit in our most comfortable BYLT Blend fabric, the Essential Tank is guaranteed to become your new go-to top for wherever the day takes you.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'black', 'subtle'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential cropped crew",
  //   route: "women's-essential-cropped-crew",
  //   collections: 'womens-tops',
  //   style: 'crews',
  //   fabric: 'bylt blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'A closet staple tailored to you, the Essential Cropped Crew has been upgraded in an all around flattering cropped fit in our most comfortable BYLT Blend fabric.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'black', 'subtle'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential leggings",
  //   route: "women's-essential-leggings",
  //   collections: 'womens-bottoms',
  //   style: 'leggings',
  //   date: new Date().getTime(),
  //   price: 7499,
  //   description:
  //     'In all around enhanced fabric and fit, our Essential Leggings will have you feeling confident and comfortable the second you put them on.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'pebble', 'atlantic'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential sports bra",
  //   route: "women's-essential-sports-bra",
  //   collections: 'womens-tops',
  //   style: 'crop tops',
  //   date: new Date().getTime(),
  //   price: 3899,
  //   description:
  //     'In all around enhanced fabric and fit, our Essential Sports Bra was designed to move with you, offering a snug fit with enough stretch for all-day comfort.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'pebble', 'atlantic'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential bodysuit",
  //   route: "women's-essential-bodysuit",
  //   collections: 'womens-tops',
  //   style: 'tanks',
  //   date: new Date().getTime(),
  //   price: 3899,
  //   description:
  //     'In all around enhanced fabric and fit, our Essential Bodysuit was designed to move with you, offering a snug fit with enough stretch for all-day comfort.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'pebble', 'white'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });
};
