import { v4 as uuidv4 } from 'uuid';

export const addDataBase = firebase => {
  const dataBase = firebase.firestore();
  /* men
    ============================================ */

  // Category: Tops
  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop-cut lux',
  //   route: 'drop-cut-lux',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description: 'Cool touch, high-cotton LUX Blend fabric.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: [
  //     'subtle',
  //     'white',
  //     'black',
  //     'heather grey',
  //     'forest',
  //     'stone',
  //     'navy',
  //     'maroon',
  //     'light heather grey',
  //     'dark heather grey',
  //     'sand',
  //     'olive',
  //     'charcoal',
  //     'atlantic',
  //     'moss',
  //     'mist',
  //     'pebble',
  //     'valencia',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //     { size: 'xxxl', isAvailable: false },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop-cut shirt',
  //   route: 'drop-cut-shirt',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'bylt blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'Meet the new and improved BYLT Blend fabric in your favorite signature drop-cut short sleeve shirt. We have worked hard to take your favorite style to the next level of comfort, fit, & functionality.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: [
  //     'black',
  //     'white',
  //     'navy',
  //     'moss',
  //     'charcoal',
  //     'maroon',
  //     'sand',
  //     'olive',
  //     'atlantic',
  //     'mist',
  //     'pebble',
  //     'valencia',
  //     'subtle',
  //     'forest',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: false },
  //     { size: 'xxl', isAvailable: false },
  //     { size: 'xxxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'drop-cut lux pocket',
  //   route: 'drop-cut-lux-pocket',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'Athletic and comfortable cut with our signature drop-cut hemline featuring our new high-cotton LUX Blend fabric.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: [
  //     'mist subtle',
  //     'navy mist',
  //     'dark heather grey pebble',
  //     'pink ice subtle',
  //     'atlantic pebble',
  //     'subtle valencia',
  //     'white mist',
  //     'forest bone',
  //     'navy swell',
  //     'bone navy',
  //     'maroon bone',
  //     'stone pacific',
  //     'pacific slate',
  //     'black charcoal',
  //     'charcoal black',
  //     'forest black',
  //     'sand pink ice',
  //     'dusk dark heather grey',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'striped drop-cut lux',
  //   route: 'striped-drop-cut-lux',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     "Elevated to a whole new level, your favorite Drop-Cut: LUX Shirt is made complete with a newly innovative striped pattern. This 'Striped Drop-Cut: LUX' is the perfect way to upgrade your everyday style.",
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: [
  //     'mist bone',
  //     'atlantic pebble',
  //     'pebble atlantic',
  //     'charcoal bone',
  //     'forest black',
  //     'navy bone',
  //     'black grey',
  //     'bone navy',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'striped drop-cut v-neck lux',
  //   route: 'striped-drop-cut-v-neck-lux',
  //   collections: 'mens-tops',
  //   style: 'drop-cuts',
  //   cut: 'drop-cuts',
  //   neck: 'v-necks',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'A fresh new take on your classic V-Neck. Your favorite style has been elevated with a V-neck collar and our signature Drop-Cut hemline perfected with the LUX fabric you love.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg'],
  //   colors: ['bone navy', 'charcoal bone', 'black grey'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: true,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'henley drop cut lux',
  //   route: 'henley-drop-cut-lux',
  //   collections: 'mens-tops',
  //   style: 'henleys',
  //   cut: 'drop-cuts',
  //   neck: 'henleys',
  //   sleeve: 'short sleeves',
  //   fabric: 'lux blend',
  //   date: new Date().getTime(),
  //   price: 3899,
  //   description:
  //     'Enjoy the best selling Drop-Cut shirt transformed into a short sleeve Henley. Our Henley Drop-Cut is here to add character and versatility to your wardrobe. This shirt is the peak of style, comfort, and function.',
  //   images: ['1.jpg', '2.jpg', '3.jpg'],
  //   colors: [
  //     'white',
  //     'black',
  //     'navy',
  //     'heather grey',
  //     'dark heather grey',
  //     'maroon',
  //     'iris',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'training shorts',
  //   route: 'training-shorts',
  //   collections: 'mens-bottoms',
  //   style: 'shorts',
  //   fabric: 'performance',
  //   date: new Date().getTime(),
  //   price: 7499,
  //   description:
  //     "Made from our NEW lightweight, breathable and ultra-stretch Performance Blend fabric, the new Training Short is built to withstand your most active days. Feel the difference that's sure to never slow you down during those high intensity training sessions.",
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'storm-camo', 'asphalt-camo', 'forest camo', 'charcoal'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: "men's elite+ drop-cut pullover",
  //   route: 'men-elite-drop-cut-pullover',
  //   collections: 'outerwear',
  //   style: 'pullovers',
  //   cut: 'drop-cuts',
  //   neck: 'hooded',
  //   sleeve: 'long sleeves',
  //   fabric: 'elite+',
  //   date: new Date().getTime(),
  //   price: 8999,
  //   description:
  //     "Made for complete comfort in all climates, our Drop-Cut Elite+ Pullover has been re-imagined in ultimate style. Now with even greater comfort, breathability, and complete all around flexibility, you've found your new go-to pullover for all seasons!",
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['storm', 'gunmetal', 'dark olive', 'sand', 'black', 'midnight'],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'everyday hat',
  //   route: 'everyday-hat',
  //   collections: 'hats-accessories',
  //   style: 'hats',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'The 100% Cotton Everyday Cap features an adjustable antique brass buckle closure to ensure the perfect fit.',
  //   images: ['1.jpg', '2.jpg', '3.jpg'],
  //   colors: ['white', 'black'],
  //   sizes: [{ size: 'os', isAvailable: true }],
  //   stock: 25,
  //   popularity: false,
  // });

  // dataBase.collection('men').add({
  //   id: uuidv4(),
  //   gender: 'men',
  //   name: 'allday boxer briefs',
  //   route: 'allday-boxer-briefs',
  //   collections: 'underwear',
  //   style: 'boxer briefs',
  //   fabric: 'all day',
  //   date: new Date().getTime(),
  //   price: 2599,
  //   description:
  //     'Our AllDay Boxer Brief Underwear style has been completely upgraded! Now in all around enhanced fabric, experience improved support with all day breathability and ultimate comfort. ',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: [
  //     'black',
  //     'sky blue navy',
  //     'forest camo',
  //     'dark olive',
  //     'asphalt camo',
  //   ],
  //   sizes: [
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //     { size: 'xl', isAvailable: true },
  //     { size: 'xxl', isAvailable: true },
  //   ],
  //   stock: 25,
  //   popularity: false,
  // });

  /* women
    ============================================ */
  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: 'the bylt crop top',
  //   route: 'the-bylt-crop-top',
  //   collections: 'womens-tops',
  //   style: 'crop tops',
  //   date: new Date().getTime(),
  //   price: 3899,
  //   discountPer: 30,
  //   description:
  //     'Figure forming with full coverage. Please Note - This Item is EXCHANGE ONLY and not eligible for return',
  //   images: ['1.jpg', '2.jpg', '3.jpg'],
  //   colors: ['grey', 'blush', 'black'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: true },
  //     { size: 'l', isAvailable: true },
  //   ],
  //   stock: 10,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's elite + joggers",
  //   route: "women's-elite-joggers",
  //   collections: 'womens-bottoms',
  //   style: 'joggers',
  //   fabric: 'elite+',
  //   date: new Date().getTime(),
  //   price: 7499,
  //   description:
  //     "Reimagined in every way, our Women’s Elite+ Joggers have been completely upgraded for even greater comfort, added durability, and all around flexibility. With the new Elite+ Fabric perfect for any season, you'll never want to take these joggers off!",
  //   images: [
  //     '1.jpg',
  //     '2.jpg',
  //     '3.jpg',
  //     '4.jpg',
  //     '5.jpg',
  //     '6.jpg',
  //     '7.jpg',
  //     '8.jpg',
  //     '9.jpg',
  //   ],
  //   colors: ['black', 'dark olive', 'sand', 'gunmetal', 'storm', 'midnight'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's everyday leggings",
  //   route: "women's-everyday-leggings",
  //   collections: 'womens-bottoms',
  //   style: 'leggings',
  //   fabric: 'elite+',
  //   date: new Date().getTime(),
  //   price: 6899,
  //   discountPer: 30,
  //   description:
  //     'Figure forming, high waisted leggings that lift and sculpt. Please note - This item is EXCHANGE ONLY and not eligible for return.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['blush', 'grey', 'black'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: true },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential tee",
  //   route: "women's-essential-tee",
  //   collections: 'womens-tops',
  //   style: 'essential tee',
  //   cut: 'crews',
  //   neck: 'crews',
  //   sleeve: 'short sleeves',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'Flattering athletic and comfortable cut with a standard straight hemline.',
  //   images: ['1.jpg', '2.jpg', '3.jpg', '4.jpg'],
  //   colors: ['black', 'white', 'blush'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });

  // dataBase.collection('women').add({
  //   id: uuidv4(),
  //   gender: 'women',
  //   name: "women's essential tank",
  //   route: "women's-essential-tank",
  //   collections: 'womens-tops',
  //   style: 'tanks',
  //   sleeve: 'no sleeves',
  //   date: new Date().getTime(),
  //   price: 2899,
  //   description:
  //     'Flattering athletic and comfortable cut with our signature drop-cut hemline.',
  //   images: ['1.png', '2.png', '3.png'],
  //   colors: ['white', 'black', 'blush'],
  //   sizes: [
  //     { size: 'xs', isAvailable: true },
  //     { size: 's', isAvailable: false },
  //     { size: 'm', isAvailable: false },
  //     { size: 'l', isAvailable: false },
  //   ],
  //   stock: 15,
  //   popularity: true,
  // });
};
