export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const GET_MEN_PRODUCTS = 'GET_MEN_PRODUCTS';
export const GET_WOMEN_PRODUCTS = 'GET_WOMEN_PRODUCTS';
export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
