export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const GET_MEN_PRODUCTS = 'GET_MEN_PRODUCTS';
export const GET_WOMEN_PRODUCTS = 'GET_WOMEN_PRODUCTS';
export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_PRODUCT_COLOR = 'GET_PRODUCT_COLOR';

// Cart actions
export const ADD_TO_CART = 'ADD_TO_CART';
export const OPEN_CART = 'OPEN_CART';
export const CLOSE_CART = 'CLOSE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const GET_PRODUCT_AMOUNT = 'GET_PRODUCT_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_TOTAL_PRODUCTS = 'COUNT_TOTAL_PRODUCTS';
export const COUNT_CART_SUBTOTAL = 'COUNT_CART_SUBTOTAL';
